### ISSUE TITLE
Use all the predicted detections for evaluation

### ISSUE THREAD

**Issue by eg4000** [skrish13/SKU110K-evaluation#3]
Please notice that the detections from the results file '/detections_output_iou_{}_{}.csv' should all be used for estimation, so you should set the evaluation parameters accordingly.

Specifically, make sure you do not truncate any detection based on its score, location, or the maximum number of detections per image.

As far as I understand, the current default parameters in the "setDetParams" function are correct:
```
self.maxDets = [300]
self.areaRngLbl = ['all']
```

(maxDets should actually be inf, but 300 is the actual upper bound for our benchmark, so it should be Ok).

However, other incorrect default values also appear in the code (e.g. maxDets=100), so I suggest that anyone who uses the code should double-check that the correct parameters are used, and that there are no other parameters that might remove some of the detections.

Thanks,
Eran.

**Comment by skrish13** [comment]
Yes, thanks for the clarification. The default parameters within function definitions hasn't been changed from COCOeval. The settings are changed in `setDetParams` to replicate the settings used in Goldman et al.
