### ISSUE TITLE
Why evaluating only 100 ImgIds?

### ISSUE THREAD

**Issue by 4vik** [skrish13/SKU110K-evaluation#4]
Hi,

thanks for this code - very useful!

Just a question though: why are you setting 

`cocoEval.params.imgIds  = range(0,100)`

 ?

Won't that only evaluate on a 100 test images, instead of the 2761 that are there?

Or am I missing something? Thanks...

**Comment by skrish13** [comment]
You're correct, that line makes it evaluate only on 100 images, i had used that to test the code as running on entire dataset took a minute or few. You can just comment it, I have made that clear now, thanks for noticing it.
