### ISSUE TITLE
How do I view TP&FP values(iou=0.5)

### ISSUE THREAD

**Issue by xincyu** [skrish13/SKU110K-evaluation#6]
hi, Thank you for the code. It's very useful to me.
However, I'm just getting started in ML ,and set a break[point](https://github.com/skrish13/SKU110K-evaluation/blob/9e30722772cddc44c613ef357a3cbacd573bbfdb/cocoapi/PythonAPI/pycocotools/cocoeval.py#L421) to view relate value(i.e. tp_sum、fp_sum）.

unfortunately,I didn't find the true value about tp and fp at iou=0.5 , because tp+fP does not equal to my number of detection .
Can you give me some help or advice.

thanks .
Leaf.

**Comment by skrish13** [comment]
For a particular category, area range and max-detections, tp and fp should be equal to the number of detections. You can check this [line](https://github.com/skrish13/SKU110K-evaluation/blob/9e30722772cddc44c613ef357a3cbacd573bbfdb/cocoapi/PythonAPI/pycocotools/cocoeval.py#L376). Maybe you were looking at the cumulative sum which is calculated later for AP purposes.

**Comment by xincyu** [comment]
thanks for your reply.
With your reminder, I know how to check the TP value I need.

check this [line](https://github.com/skrish13/SKU110K-evaluation/blob/9e30722772cddc44c613ef357a3cbacd573bbfdb/cocoapi/PythonAPI/pycocotools/cocoeval.py#L380)，I saw the maximum TP and the minimum fP (at iou=0.5), When I verify the sum, it  is equal to the number of checks（dets_num），so It's right.
